from __future__ import annotations

import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../../")))

from scripts.reporting.build_reporting_layer import (
    TELEGRAM_MESSAGE_FILE,
    build_reporting_layer,
    write_outputs,
)


def build_telegram_summary_text() -> str:
    _, _, telegram_text = build_reporting_layer()
    return telegram_text


def save_summary(text: str) -> None:
    TELEGRAM_MESSAGE_FILE.parent.mkdir(parents=True, exist_ok=True)
    TELEGRAM_MESSAGE_FILE.write_text(text, encoding="utf-8")


def main() -> None:
    dashboard, log_row, telegram_text = build_reporting_layer()
    write_outputs(dashboard, log_row, telegram_text)
    print("Telegram summary generated by authoritative Reporting Layer.")


if __name__ == "__main__":
    main()
